# Generated by Django 5.0.3 on 2024-03-27 02:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('materia', models.CharField(choices=[('Programación', 'Opción 1'), ('Comunicacion', 'Opción 2'), ('Diseño', 'Opción3')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacionesDjango.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_nombre', models.CharField(max_length=50)),
                ('cursos', models.ManyToManyField(to='relacionesDjango.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('contraseña', models.CharField(max_length=100)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relacionesDjango.estudiante')),
            ],
        ),
    ]
